[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]

remappings = [
      "@uniswap/v3-periphery/contracts/=node_modules/@uniswap/v3-periphery/contracts/",
      "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
      "@uniswap/v3-core/contracts/=node_modules/@uniswap/v3-core/contracts/",
      "@uniswap/lib/contracts/=node_modules/@uniswap/lib/contracts/",
      ]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
